# permissions for end users to edit cdpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cdpipeline-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: empty-operator
    app.kubernetes.io/part-of: empty-operator
    app.kubernetes.io/managed-by: kustomize
  name: cdpipeline-editor-role
rules:
- apiGroups:
  - v2.edp.epam.com
  resources:
  - cdpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v2.edp.epam.com
  resources:
  - cdpipelines/status
  verbs:
  - get
