# permissions for end users to view stages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: stage-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: empty-operator
    app.kubernetes.io/part-of: empty-operator
    app.kubernetes.io/managed-by: kustomize
  name: stage-viewer-role
rules:
- apiGroups:
  - v2.edp.epam.com
  resources:
  - stages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - v2.edp.epam.com
  resources:
  - stages/status
  verbs:
  - get
