global:
  edpName: ""
  platform: "openshift"
  kioskEnabled: "true"

name: cd-pipeline-operator
annotations: {}
nodeSelector: {}
tolerations: []
affinity:
image:
  repository: epamedp/cd-pipeline-operator
  # if not defined then .Chart.AppVersion is used
  tag:
imagePullPolicy: "IfNotPresent"

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi
