global:
  edpName: ""
  platform: "openshift"
  kioskEnabled: true

name: cd-pipeline-operator
annotations: {}
nodeSelector: {}
tolerations: []
affinity:
image:
  name: epamedp/cd-pipeline-operator
  # if not defined then .Chart.AppVersion is used
  version:

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi
